### ISSUE TITLE
statistics sql should not include statement terminator

### ISSUE THREAD

**Issue by bjornhilstad** [difi/vefa-srest#11]
The /statistics resource fails with ORA-00933: SQL command not properly ended when using Oracle.

This is because the SQL string includes a statement terminator. Unsure if this also is a problem on other databases.

If PeppolMessageRepositoryImpl is changed from this:
final String orderBy = "\nORDER BY account.name ASC; ";
to this:
final String orderBy = "\nORDER BY account.name ASC";
it works on Oracle.

**Comment by steinarcook** [comment]
Fixed by Bjørn Kristian Hilstad
